### ISSUE TITLE
Run Camel K jdbc locally with JBang

### ISSUE THREAD

**Issue by cheeghi** [openshift-integration/camel-k-example-jdbc#18]
Hi, I'm trying to run this example locally with JBang, but I can't make it work. Below the details.

Integration DSL KamelKJdbcRouter.java:
```
import org.apache.camel.builder.RouteBuilder;

// camel-k: dependency=camel:jdbc
// camel-k: dependency=mvn:io.quarkus:quarkus-jdbc-postgresql

public class KamelKJdbcRouter extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        from("timer://foo?period=10000")
                .setBody(constant("SELECT data FROM test LIMIT 5 OFFSET 0"))
                .to("jdbc:default")
                .to("log:info");
    }

}
```
application.properties:
```
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/test
quarkus.datasource.username=postgresadmin
quarkus.datasource.password=admin123
quarkus.datasource.db-kind=postgresql
```
Command run:
```
jbang run -Dcamel.jbang.version=4.2.0 camel@apache/camel run KamelKJdbcRouter.java
```
The error I get:
```
Caused by: java.lang.IllegalArgumentException: No default DataSource found in the registry
        at org.apache.camel.component.jdbc.JdbcComponent.createEndpoint(JdbcComponent.java:67)
        at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:170)
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:804)
        ... 34 more
```
It seems like quarkus build isn't kicking in and the datasource is not being created.
The example works fine on k8s.
I'm using camel-k with jbang with other components (like activemq) and they work fine.

Do you have any idea? Thanks!

**Comment by cheeghi** [comment]
Answer on [stackoverflow](https://stackoverflow.com/questions/78328521/run-camel-k-jdbc-locally-with-jbang).
